name: Database Backup

#  on:
#    schedule:
#      - cron: "0 0 * * *"
on:
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Assume IAM Role
        id: iam
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::274747834986:role/buzzed_trivia_database_role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve private key from AWS Secrets Manager
        run: |
          export PRIVATE_KEY=$(aws secretsmanager get-secret-value --secret-id buzzed-trivia/private-key --query 'SecretString' --output text)

      - name: Create backup and upload to S3
        run: |
          echo "$PRIVATE_KEY" > buzzed-trivia.pem
          chmod 600 buzzed-trivia.pem
          ssh -o StrictHostKeyChecking=no -i buzzed-trivia.pem ubuntu@44.203.70.232 'pg_dump -U postgres -h localhost buzzed_trivia_hive > backup.sql'
          aws s3 cp backup.sql s3://buzzed-trivia-database-backups/backup.sql

      - name: Cleanup
        run: |
          rm -f private_key.pem
