name: Database Backup

#on:
#  push:
#    branches:
#      - main
on:
  workflow_dispatch:


jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BUZZED_TRIVIA_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

      - name: SSH into remote host and backup database
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.USER }}@${{ secrets.EC2_PUBLIC_IP }} <<'ENDSSH'
            cd /etc/postgresql
            PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} sudo -u postgres pg_dump -U postgres the_hive > /var/www/html/backup.sql
            sudo apt-get install -y awscli
            aws s3 cp backup.sql s3://buzzed-trivia-database-backups/
          ENDSSH
