name: Database Backup

#on:
#  push:
#    branches:
#      - main
on:
  schedule:
    - cron: "0 0 * * *" # Run every day


jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BUZZED_TRIVIA_PRIVATE_KEY }}

      - name: SSH into remote host and backup database
        run: |
          export AWS_ACCESS_KEY
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.USER }}@${{ secrets.EC2_PUBLIC_IP }} <<'ENDSSH'
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            cd /etc/postgresql
            PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} sudo -u postgres pg_dump -U postgres the_hive > /var/www/html/backup.sql
            cd /var/www/html
            sudo apt-get install -y awscli
            aws s3 cp backup.sql s3://buzzed-trivia-database-backups/
          ENDSSH
