name: Database Initialization

on:
  workflow_dispatch:

jobs:
  initialize_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BUZZED_TRIVIA_PRIVATE_KEY }}

      - name: SSH into remote host and execute SQL scripts
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          # Set the target directory
          target_directory="/var/www/html/buzzed-trivia-database/deploy-scripts/"
          
          # Iterate through SQL scripts in the target directory
          for script in "$target_directory"*.sql; do
            PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h localhost -U postgres -d the_hive -f "$script"
          done
